"""add autofill_drafts table

Revision ID: 6df562df5dd8
Revises: d1e67f5518ce
Create Date: 2026-07-25 14:44:46.792890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df562df5dd8'
down_revision: Union[str, None] = 'd1e67f5518ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autofill_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('ats_platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('screenshot_base64', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autofill_drafts_job_listing_id'), 'autofill_drafts', ['job_listing_id'], unique=False)
    op.create_index(op.f('ix_autofill_drafts_resume_id'), 'autofill_drafts', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autofill_drafts_resume_id'), table_name='autofill_drafts')
    op.drop_index(op.f('ix_autofill_drafts_job_listing_id'), table_name='autofill_drafts')
    op.drop_table('autofill_drafts')
    # ### end Alembic commands ###
