"""add interview_preps table

Revision ID: d1e67f5518ce
Revises: 8e9345df22b0
Create Date: 2026-07-24 22:00:00.600861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e67f5518ce'
down_revision: Union[str, None] = '8e9345df22b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_analysis_id', sa.Integer(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jd_analysis_id'], ['jd_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_preps_jd_analysis_id'), 'interview_preps', ['jd_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_preps_jd_analysis_id'), table_name='interview_preps')
    op.drop_table('interview_preps')
    # ### end Alembic commands ###
